# Generated by Django 4.1.3 on 2022-12-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_text', models.CharField(max_length=100, verbose_name='Alerta')),
                ('periodicity', models.CharField(blank=True, choices=[('Diario', 'Diario'), ('Semanal', 'Semanal')], max_length=10)),
            ],
        ),
    ]
