# Generated by Django 4.1.3 on 2022-12-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titulo')),
                ('date_publish', models.DateField()),
                ('subtitulo', models.CharField(max_length=100)),
                ('sub_subtitulo', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=50, verbose_name='Salario')),
                ('description', models.CharField(max_length=10000, verbose_name='Descripcion')),
                ('company', models.CharField(default='', max_length=50, verbose_name='Empresa')),
                ('type', models.CharField(choices=[('Presencial', 'Presencial'), ('Hibrido', 'Hibrido'), ('Remoto', 'Remoto')], max_length=50, verbose_name='Tipo')),
                ('url_postulation', models.URLField(max_length=5000)),
                ('location', models.CharField(default='', max_length=100, verbose_name='Ubacion')),
            ],
        ),
    ]
